version: '3.9'
services:
  bacchecker-institution-portal:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev -- --host 0.0.0.0 --port 5173
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      - /app/dist